sudo: required
services:
  - docker

before_install:
  - docker build -t acxmatos/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run acxmatos/multi-docker-client-test npm test -- --coverage

after_success:
  - docker build -t acxmatos/multi-docker-client ./client
  - docker build -t acxmatos/multi-docker-nginx ./nginx
  - docker build -t acxmatos/multi-docker-server ./server
  - docker build -t acxmatos/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push acxmatos/multi-docker-client
  - docker push acxmatos/multi-docker-nginx
  - docker push acxmatos/multi-docker-server
  - docker push acxmatos/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-891727119958
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY